server:
  port: 8443
  ssl:
    key-store: classpath:mykeys.jks
    key-store-password: letmein
    key-password: letmein

logging:
  path: /tmp/
  file: BookWorm.log
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

amazon:
  associateId: hubuma-20

spring:
  profiles:
    active: development

management:
  endpoint:
    beans:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

info:
  contact:
    email: support@myreadinglist.com
    phone: 1-888-555-1971
